--정답 테이블 설정 (Q_NUMBER : 문제번호 / A_NUMBER : 답안지 번호)
CREATE TABLE ANSWER_A (
  Q_NUMBER NUMBER NOT NULL,
  A_NUMBER NUMBER
);

-- 문제 번호에 기본키 제약사항 추가
ALTER TABLE ANSWER_A  MODIFY Q_NUMBER PRIMARY KEY;

--문제와 정답 데이터 삽입
INSERT INTO ANSWER_A  VALUES(1,3);
INSERT INTO ANSWER_A  VALUES(2,2);
INSERT INTO ANSWER_A  VALUES(3,1);
INSERT INTO ANSWER_A  VALUES(4,1);
INSERT INTO ANSWER_A  VALUES(5,4);
INSERT INTO ANSWER_A  VALUES(6,3);
INSERT INTO ANSWER_A  VALUES(7,2);
INSERT INTO ANSWER_A  VALUES(8,4);
INSERT INTO ANSWER_A  VALUES(9,4);
INSERT INTO ANSWER_A  VALUES(10,1);
INSERT INTO ANSWER_A  VALUES(11,2);
INSERT INTO ANSWER_A  VALUES(12,3);
INSERT INTO ANSWER_A  VALUES(13,3);
INSERT INTO ANSWER_A  VALUES(14,4);
INSERT INTO ANSWER_A  VALUES(15,3);
INSERT INTO ANSWER_A  VALUES(16,2);
INSERT INTO ANSWER_A  VALUES(17,1);
INSERT INTO ANSWER_A  VALUES(18,1);
INSERT INTO ANSWER_A  VALUES(19,4);
INSERT INTO ANSWER_A  VALUES(20,3);

--확정
COMMIT;

SELECT* FROM ANSWER_A;